// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	managementv1 "github.com/skevetter/api/pkg/apis/management/v1"
	versioned "github.com/skevetter/api/pkg/clientset/versioned"
	internalinterfaces "github.com/skevetter/api/pkg/informers/externalversions/internalinterfaces"
	v1 "github.com/skevetter/api/pkg/listers/management/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DevsyUpgradeInformer provides access to a shared informer and lister for
// DevsyUpgrades.
type DevsyUpgradeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.DevsyUpgradeLister
}

type devsyUpgradeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewDevsyUpgradeInformer constructs a new informer for DevsyUpgrade type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDevsyUpgradeInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDevsyUpgradeInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredDevsyUpgradeInformer constructs a new informer for DevsyUpgrade type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDevsyUpgradeInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ManagementV1().DevsyUpgrades().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ManagementV1().DevsyUpgrades().Watch(context.TODO(), options)
			},
		},
		&managementv1.DevsyUpgrade{},
		resyncPeriod,
		indexers,
	)
}

func (f *devsyUpgradeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDevsyUpgradeInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *devsyUpgradeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&managementv1.DevsyUpgrade{}, f.defaultInformer)
}

func (f *devsyUpgradeInformer) Lister() v1.DevsyUpgradeLister {
	return v1.NewDevsyUpgradeLister(f.Informer().GetIndexer())
}
