// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apismanagementv1 "github.com/skevetter/api/pkg/apis/management/v1"
	versioned "github.com/skevetter/api/pkg/clientset/versioned"
	internalinterfaces "github.com/skevetter/api/pkg/informers/externalversions/internalinterfaces"
	managementv1 "github.com/skevetter/api/pkg/listers/management/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TranslateDevsyResourceNameInformer provides access to a shared informer and lister for
// TranslateDevsyResourceNames.
type TranslateDevsyResourceNameInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() managementv1.TranslateDevsyResourceNameLister
}

type translateDevsyResourceNameInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewTranslateDevsyResourceNameInformer constructs a new informer for TranslateDevsyResourceName type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTranslateDevsyResourceNameInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTranslateDevsyResourceNameInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredTranslateDevsyResourceNameInformer constructs a new informer for TranslateDevsyResourceName type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTranslateDevsyResourceNameInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ManagementV1().TranslateDevsyResourceNames().List(context.Background(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ManagementV1().TranslateDevsyResourceNames().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ManagementV1().TranslateDevsyResourceNames().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ManagementV1().TranslateDevsyResourceNames().Watch(ctx, options)
			},
		},
		&apismanagementv1.TranslateDevsyResourceName{},
		resyncPeriod,
		indexers,
	)
}

func (f *translateDevsyResourceNameInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTranslateDevsyResourceNameInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *translateDevsyResourceNameInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apismanagementv1.TranslateDevsyResourceName{}, f.defaultInformer)
}

func (f *translateDevsyResourceNameInformer) Lister() managementv1.TranslateDevsyResourceNameLister {
	return managementv1.NewTranslateDevsyResourceNameLister(f.Informer().GetIndexer())
}
