// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	managementv1 "github.com/skevetter/api/pkg/apis/management/v1"
	scheme "github.com/skevetter/api/pkg/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DevsyUpgradesGetter has a method to return a DevsyUpgradeInterface.
// A group's client should implement this interface.
type DevsyUpgradesGetter interface {
	DevsyUpgrades() DevsyUpgradeInterface
}

// DevsyUpgradeInterface has methods to work with DevsyUpgrade resources.
type DevsyUpgradeInterface interface {
	Create(ctx context.Context, loftUpgrade *managementv1.DevsyUpgrade, opts metav1.CreateOptions) (*managementv1.DevsyUpgrade, error)
	Update(ctx context.Context, loftUpgrade *managementv1.DevsyUpgrade, opts metav1.UpdateOptions) (*managementv1.DevsyUpgrade, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, loftUpgrade *managementv1.DevsyUpgrade, opts metav1.UpdateOptions) (*managementv1.DevsyUpgrade, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*managementv1.DevsyUpgrade, error)
	List(ctx context.Context, opts metav1.ListOptions) (*managementv1.DevsyUpgradeList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *managementv1.DevsyUpgrade, err error)
	DevsyUpgradeExpansion
}

// loftUpgrades implements DevsyUpgradeInterface
type loftUpgrades struct {
	*gentype.ClientWithList[*managementv1.DevsyUpgrade, *managementv1.DevsyUpgradeList]
}

// newDevsyUpgrades returns a DevsyUpgrades
func newDevsyUpgrades(c *ManagementV1Client) *loftUpgrades {
	return &loftUpgrades{
		gentype.NewClientWithList[*managementv1.DevsyUpgrade, *managementv1.DevsyUpgradeList](
			"devsyupgrades",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementv1.DevsyUpgrade { return &managementv1.DevsyUpgrade{} },
			func() *managementv1.DevsyUpgradeList { return &managementv1.DevsyUpgradeList{} },
		),
	}
}
