// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/skevetter/api/pkg/apis/management/v1"
	scheme "github.com/skevetter/api/pkg/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DevsyUpgradesGetter has a method to return a DevsyUpgradeInterface.
// A group's client should implement this interface.
type DevsyUpgradesGetter interface {
	DevsyUpgrades() DevsyUpgradeInterface
}

// DevsyUpgradeInterface has methods to work with DevsyUpgrade resources.
type DevsyUpgradeInterface interface {
	Create(ctx context.Context, devsyUpgrade *v1.DevsyUpgrade, opts metav1.CreateOptions) (*v1.DevsyUpgrade, error)
	Update(ctx context.Context, devsyUpgrade *v1.DevsyUpgrade, opts metav1.UpdateOptions) (*v1.DevsyUpgrade, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, devsyUpgrade *v1.DevsyUpgrade, opts metav1.UpdateOptions) (*v1.DevsyUpgrade, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.DevsyUpgrade, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.DevsyUpgradeList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DevsyUpgrade, err error)
	DevsyUpgradeExpansion
}

// devsyUpgrades implements DevsyUpgradeInterface
type devsyUpgrades struct {
	*gentype.ClientWithList[*v1.DevsyUpgrade, *v1.DevsyUpgradeList]
}

// newDevsyUpgrades returns a DevsyUpgrades
func newDevsyUpgrades(c *ManagementV1Client) *devsyUpgrades {
	return &devsyUpgrades{
		gentype.NewClientWithList[*v1.DevsyUpgrade, *v1.DevsyUpgradeList](
			"devsyupgrades",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1.DevsyUpgrade { return &v1.DevsyUpgrade{} },
			func() *v1.DevsyUpgradeList { return &v1.DevsyUpgradeList{} }),
	}
}
