// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/skevetter/api/pkg/apis/management/v1"
	scheme "github.com/skevetter/api/pkg/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TranslateDevsyResourceNamesGetter has a method to return a TranslateDevsyResourceNameInterface.
// A group's client should implement this interface.
type TranslateDevsyResourceNamesGetter interface {
	TranslateDevsyResourceNames() TranslateDevsyResourceNameInterface
}

// TranslateDevsyResourceNameInterface has methods to work with TranslateDevsyResourceName resources.
type TranslateDevsyResourceNameInterface interface {
	Create(ctx context.Context, translateDevsyResourceName *v1.TranslateDevsyResourceName, opts metav1.CreateOptions) (*v1.TranslateDevsyResourceName, error)
	Update(ctx context.Context, translateDevsyResourceName *v1.TranslateDevsyResourceName, opts metav1.UpdateOptions) (*v1.TranslateDevsyResourceName, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, translateDevsyResourceName *v1.TranslateDevsyResourceName, opts metav1.UpdateOptions) (*v1.TranslateDevsyResourceName, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.TranslateDevsyResourceName, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.TranslateDevsyResourceNameList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.TranslateDevsyResourceName, err error)
	TranslateDevsyResourceNameExpansion
}

// translateDevsyResourceNames implements TranslateDevsyResourceNameInterface
type translateDevsyResourceNames struct {
	*gentype.ClientWithList[*v1.TranslateDevsyResourceName, *v1.TranslateDevsyResourceNameList]
}

// newTranslateDevsyResourceNames returns a TranslateDevsyResourceNames
func newTranslateDevsyResourceNames(c *ManagementV1Client) *translateDevsyResourceNames {
	return &translateDevsyResourceNames{
		gentype.NewClientWithList[*v1.TranslateDevsyResourceName, *v1.TranslateDevsyResourceNameList](
			"translatedevsyresourcenames",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1.TranslateDevsyResourceName { return &v1.TranslateDevsyResourceName{} },
			func() *v1.TranslateDevsyResourceNameList { return &v1.TranslateDevsyResourceNameList{} }),
	}
}
