// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	managementv1 "github.com/skevetter/api/pkg/apis/management/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DevsyUpgradeLister helps list DevsyUpgrades.
// All objects returned here must be treated as read-only.
type DevsyUpgradeLister interface {
	// List lists all DevsyUpgrades in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*managementv1.DevsyUpgrade, err error)
	// Get retrieves the DevsyUpgrade from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*managementv1.DevsyUpgrade, error)
	DevsyUpgradeListerExpansion
}

// loftUpgradeLister implements the DevsyUpgradeLister interface.
type loftUpgradeLister struct {
	listers.ResourceIndexer[*managementv1.DevsyUpgrade]
}

// NewDevsyUpgradeLister returns a new DevsyUpgradeLister.
func NewDevsyUpgradeLister(indexer cache.Indexer) DevsyUpgradeLister {
	return &loftUpgradeLister{listers.New[*managementv1.DevsyUpgrade](indexer, managementv1.Resource("devsyupgrade"))}
}
