// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/skevetter/api/pkg/apis/management/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// DevsyUpgradeLister helps list DevsyUpgrades.
// All objects returned here must be treated as read-only.
type DevsyUpgradeLister interface {
	// List lists all DevsyUpgrades in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.DevsyUpgrade, err error)
	// Get retrieves the DevsyUpgrade from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.DevsyUpgrade, error)
	DevsyUpgradeListerExpansion
}

// devsyUpgradeLister implements the DevsyUpgradeLister interface.
type devsyUpgradeLister struct {
	listers.ResourceIndexer[*v1.DevsyUpgrade]
}

// NewDevsyUpgradeLister returns a new DevsyUpgradeLister.
func NewDevsyUpgradeLister(indexer cache.Indexer) DevsyUpgradeLister {
	return &devsyUpgradeLister{listers.New[*v1.DevsyUpgrade](indexer, v1.Resource("devsyupgrade"))}
}
