// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/skevetter/api/pkg/apis/management/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// TranslateDevsyResourceNameLister helps list TranslateDevsyResourceNames.
// All objects returned here must be treated as read-only.
type TranslateDevsyResourceNameLister interface {
	// List lists all TranslateDevsyResourceNames in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.TranslateDevsyResourceName, err error)
	// Get retrieves the TranslateDevsyResourceName from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.TranslateDevsyResourceName, error)
	TranslateDevsyResourceNameListerExpansion
}

// translateDevsyResourceNameLister implements the TranslateDevsyResourceNameLister interface.
type translateDevsyResourceNameLister struct {
	listers.ResourceIndexer[*v1.TranslateDevsyResourceName]
}

// NewTranslateDevsyResourceNameLister returns a new TranslateDevsyResourceNameLister.
func NewTranslateDevsyResourceNameLister(indexer cache.Indexer) TranslateDevsyResourceNameLister {
	return &translateDevsyResourceNameLister{listers.New[*v1.TranslateDevsyResourceName](indexer, v1.Resource("translatedevsyresourcename"))}
}
