// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/skevetter/api/pkg/apis/management/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTranslateDevsyResourceNames implements TranslateDevsyResourceNameInterface
type FakeTranslateDevsyResourceNames struct {
	Fake *FakeManagementV1
}

var translatedevsyresourcenamesResource = v1.SchemeGroupVersion.WithResource("translatedevsyresourcenames")

var translatedevsyresourcenamesKind = v1.SchemeGroupVersion.WithKind("TranslateDevsyResourceName")

// Get takes name of the translateDevsyResourceName, and returns the corresponding translateDevsyResourceName object, and an error if there is any.
func (c *FakeTranslateDevsyResourceNames) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.TranslateDevsyResourceName, err error) {
	emptyResult := &v1.TranslateDevsyResourceName{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(translatedevsyresourcenamesResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.TranslateDevsyResourceName), err
}

// List takes label and field selectors, and returns the list of TranslateDevsyResourceNames that match those selectors.
func (c *FakeTranslateDevsyResourceNames) List(ctx context.Context, opts metav1.ListOptions) (result *v1.TranslateDevsyResourceNameList, err error) {
	emptyResult := &v1.TranslateDevsyResourceNameList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(translatedevsyresourcenamesResource, translatedevsyresourcenamesKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.TranslateDevsyResourceNameList{ListMeta: obj.(*v1.TranslateDevsyResourceNameList).ListMeta}
	for _, item := range obj.(*v1.TranslateDevsyResourceNameList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested translateDevsyResourceNames.
func (c *FakeTranslateDevsyResourceNames) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(translatedevsyresourcenamesResource, opts))
}

// Create takes the representation of a translateDevsyResourceName and creates it.  Returns the server's representation of the translateDevsyResourceName, and an error, if there is any.
func (c *FakeTranslateDevsyResourceNames) Create(ctx context.Context, translateDevsyResourceName *v1.TranslateDevsyResourceName, opts metav1.CreateOptions) (result *v1.TranslateDevsyResourceName, err error) {
	emptyResult := &v1.TranslateDevsyResourceName{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(translatedevsyresourcenamesResource, translateDevsyResourceName, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.TranslateDevsyResourceName), err
}

// Update takes the representation of a translateDevsyResourceName and updates it. Returns the server's representation of the translateDevsyResourceName, and an error, if there is any.
func (c *FakeTranslateDevsyResourceNames) Update(ctx context.Context, translateDevsyResourceName *v1.TranslateDevsyResourceName, opts metav1.UpdateOptions) (result *v1.TranslateDevsyResourceName, err error) {
	emptyResult := &v1.TranslateDevsyResourceName{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(translatedevsyresourcenamesResource, translateDevsyResourceName, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.TranslateDevsyResourceName), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTranslateDevsyResourceNames) UpdateStatus(ctx context.Context, translateDevsyResourceName *v1.TranslateDevsyResourceName, opts metav1.UpdateOptions) (result *v1.TranslateDevsyResourceName, err error) {
	emptyResult := &v1.TranslateDevsyResourceName{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceActionWithOptions(translatedevsyresourcenamesResource, "status", translateDevsyResourceName, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.TranslateDevsyResourceName), err
}

// Delete takes name of the translateDevsyResourceName and deletes it. Returns an error if one occurs.
func (c *FakeTranslateDevsyResourceNames) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(translatedevsyresourcenamesResource, name, opts), &v1.TranslateDevsyResourceName{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTranslateDevsyResourceNames) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionActionWithOptions(translatedevsyresourcenamesResource, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1.TranslateDevsyResourceNameList{})
	return err
}

// Patch applies the patch and returns the patched translateDevsyResourceName.
func (c *FakeTranslateDevsyResourceNames) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.TranslateDevsyResourceName, err error) {
	emptyResult := &v1.TranslateDevsyResourceName{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(translatedevsyresourcenamesResource, name, pt, data, opts, subresources...), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.TranslateDevsyResourceName), err
}
