// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/skevetter/api/pkg/apis/management/v1"
	managementv1 "github.com/skevetter/api/pkg/clientset/versioned/typed/management/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeTranslateDevsyResourceNames implements TranslateDevsyResourceNameInterface
type fakeTranslateDevsyResourceNames struct {
	*gentype.FakeClientWithList[*v1.TranslateDevsyResourceName, *v1.TranslateDevsyResourceNameList]
	Fake *FakeManagementV1
}

func newFakeTranslateDevsyResourceNames(fake *FakeManagementV1) managementv1.TranslateDevsyResourceNameInterface {
	return &fakeTranslateDevsyResourceNames{
		gentype.NewFakeClientWithList[*v1.TranslateDevsyResourceName, *v1.TranslateDevsyResourceNameList](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("translatedevsyresourcenames"),
			v1.SchemeGroupVersion.WithKind("TranslateDevsyResourceName"),
			func() *v1.TranslateDevsyResourceName { return &v1.TranslateDevsyResourceName{} },
			func() *v1.TranslateDevsyResourceNameList { return &v1.TranslateDevsyResourceNameList{} },
			func(dst, src *v1.TranslateDevsyResourceNameList) { dst.ListMeta = src.ListMeta },
			func(list *v1.TranslateDevsyResourceNameList) []*v1.TranslateDevsyResourceName {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.TranslateDevsyResourceNameList, items []*v1.TranslateDevsyResourceName) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
