// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/skevetter/api/pkg/apis/management/v1"
	managementv1 "github.com/skevetter/api/pkg/clientset/versioned/typed/management/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeDevsyUpgrades implements DevsyUpgradeInterface
type fakeDevsyUpgrades struct {
	*gentype.FakeClientWithList[*v1.DevsyUpgrade, *v1.DevsyUpgradeList]
	Fake *FakeManagementV1
}

func newFakeDevsyUpgrades(fake *FakeManagementV1) managementv1.DevsyUpgradeInterface {
	return &fakeDevsyUpgrades{
		gentype.NewFakeClientWithList[*v1.DevsyUpgrade, *v1.DevsyUpgradeList](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("devsyupgrades"),
			v1.SchemeGroupVersion.WithKind("DevsyUpgrade"),
			func() *v1.DevsyUpgrade { return &v1.DevsyUpgrade{} },
			func() *v1.DevsyUpgradeList { return &v1.DevsyUpgradeList{} },
			func(dst, src *v1.DevsyUpgradeList) { dst.ListMeta = src.ListMeta },
			func(list *v1.DevsyUpgradeList) []*v1.DevsyUpgrade { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.DevsyUpgradeList, items []*v1.DevsyUpgrade) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
